version: "3.8"

services:
  selenium:
    image: selenium/standalone-firefox
    networks:
      - app-network

  web-parser:
    depends_on:
      - selenium
    build: ./web_parser
    env_file:
      - ./credentials/.env
    environment:
      - WISHPICK_INSIDE_DOCKER=true
    volumes:
      - ./credentials/:/app/credentials:ro
    networks:
      - app-network

  bot:
    build: ./bot
    env_file:
      - ./credentials/.env
    environment:
      - WISHPICK_INSIDE_DOCKER=true
    volumes:
      - ./credentials/:/app/credentials:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  credentials: